version: "3"
services:
  db:
#    platform: linux/x86_64
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: my-db
    environment:
      - MYSQL_DATABASE=social-media-database
      - MYSQL_USER=social-media-user
      - MYSQL_PASSWORD=dummypassword
      - MYSQL_ROOT_PASSWORD=dummypassword
volumes:
  db-store: